server:
  port: 8080

spring:
  application:
    name: vehicle-service
  
  config:
    import: optional:configserver:http://localhost:8888
    
#    old configs

#  datasource:
#    url: jdbc:h2:mem:iotdb
#    driverClassName: org.h2.Driver
#    username: sa
#    password: password
  
  jpa:
    defer-datasource-initialization: true
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  
  h2:
    console:
      enabled: true
  
#  Datasource 1
  datasource:
    jdbcUrl: jdbc:h2:mem:iotdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 

#  Datasource 2
  second-datasource:
    jdbcUrl: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 

hibernate:
  hbm2ddl:
    auto: update

alert-configuration:
    speed-limit: 90

custom:
  page-size: "30"
  telemetry-scheduler:
    enabled: false
    initial-delay: 5000
    fixed-delay: 5000
    cron: "0 30 18 * * *"
    time-interval-in-seconds: 86400
  excel-upload-config:
    vehicle-sheet-name: "VehicleList"